project.home: /Users/macid/workspace/new-commerce
server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: NEO-COMMERCE
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-db?useSSL=false&serverTimezone=Asia/Jakarta
    username: root
    password: secret
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  messages:
    basename: i18n/messages
loader:
  path: ${project.home}/lib

logging:
  level:
    ROOT: error
    org.springframework:
      web: info
    com.moinves.payment: info
    org:
      hibernate: error
  path: logs
  file: ${logging.path}/${spring.application.name}.log
  pattern.level: '%X{req_id} %5p'
